name: "font-generator"
version: "1.0.0"
github: ""
license: BSD3
author: "Ziphil"
maintainer: ""
copyright: "2019 Ziphil"

description: ""

dependencies:
  - base >= 4.7 && < 5
  - array
  - containers
  - deepseq
  - diagrams
  - diagrams-contrib
  - diagrams-lib
  - diagrams-svg
  - filepath
  - hspec
  - path

library:
  source-dirs: source

executables:
  font-generator-exe:
    main: Main.hs
    source-dirs: application
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - font-generator

tests:
  font-generator-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - font-generator
